# Generated by Django 5.0.6 on 2024-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10, max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
