# Generated by Django 5.0.6 on 2024-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product_category_product_price_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default='', upload_to='ecom/images'),
        ),
    ]
